{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "name": "CostoConversion",
    "culture": "es-HN",
    "dataSources": [
      {
        "name": "SqlServer cubo-intermoda CRONO_INTERMODA",
        "connectionString": "Provider=SQLNCLI11;Data Source=cubo-intermoda;Initial Catalog=CRONO_INTERMODA;Persist Security Info=false;User ID=dtsitm",
        "impersonationMode": "impersonateAccount",
        "account": "intermoda\\dtsitm",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer cubo-intermoda",
        "connectionString": "Provider=SQLNCLI11;Data Source=cubo-intermoda;Persist Security Info=false;Initial Catalog=CRONO_INTERMODA;User ID=dtsitm",
        "impersonationMode": "impersonateAccount",
        "account": "intermoda\\dtsitm",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "CostoConversion",
        "columns": [
          {
            "name": "IdCostoConversion",
            "dataType": "int64",
            "sourceColumn": "IdCostoConversion",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Linea",
            "dataType": "string",
            "sourceColumn": "Linea",
            "sourceProviderType": "Char"
          },
          {
            "name": "CuentaContable",
            "dataType": "string",
            "sourceColumn": "CuentaContable",
            "sourceProviderType": "WChar"
          },
          {
            "name": "TipoEmpleado",
            "dataType": "string",
            "sourceColumn": "TipoEmpleado",
            "sourceProviderType": "Char"
          },
          {
            "name": "AñoSemana",
            "dataType": "int64",
            "sourceColumn": "Semana",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Seccion",
            "dataType": "string",
            "sourceColumn": "Seccion",
            "sourceProviderType": "Char"
          },
          {
            "name": "Costo",
            "dataType": "double",
            "sourceColumn": "Costo",
            "formatString": "#,0.00",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "MinMeta",
            "dataType": "double",
            "sourceColumn": "MinMeta",
            "formatString": "#,0",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "MinProd",
            "dataType": "double",
            "sourceColumn": "MinProd",
            "formatString": "#,0",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "PiezasLeidas",
            "dataType": "int64",
            "sourceColumn": "PiezasLeidas",
            "sourceProviderType": "Integer"
          },
          {
            "name": "FechaAlta",
            "dataType": "dateTime",
            "sourceColumn": "FechaAlta",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "FechaModificacion",
            "dataType": "dateTime",
            "sourceColumn": "FechaModificacion",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "type": "calculated",
            "name": "Semana",
            "dataType": "int64",
            "isDataTypeInferred": false,
            "expression": " RIGHT(CostoConversion[AñoSemana],2)",
            "formatString": "0"
          },
          {
            "type": "calculated",
            "name": "Año",
            "dataType": "int64",
            "isDataTypeInferred": false,
            "expression": " left(CostoConversion[AñoSemana],4)",
            "formatString": "0"
          },
          {
            "type": "calculated",
            "name": "LineaID",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "SWITCH(CostoConversion[Linea],\"Denim\", 10, \"Tejido Punto\", 34, \"Estampado\",35)"
          },
          {
            "type": "calculated",
            "name": "CostoTotal",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "DIVIDE(CostoConversion[Costo],CostoConversion[PiezasLeidas],0)",
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "MinPlanta",
            "dataType": "int64",
            "sourceColumn": "MinPlanta",
            "formatString": "#,0"
          },
          {
            "type": "calculated",
            "name": "IDLineaAñoSemana",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "CONCATENATE(CostoConversion[LineaID],CostoConversion[AñoSemana])"
          },
          {
            "name": "Piezas",
            "dataType": "int64",
            "sourceColumn": "Piezas",
            "formatString": "#,0"
          },
          {
            "name": "Min_Metas",
            "dataType": "double",
            "sourceColumn": "Min_Metas",
            "formatString": "#,0"
          },
          {
            "name": "Min_Producidos",
            "dataType": "double",
            "sourceColumn": "Min_Producidos",
            "formatString": "#,0"
          },
          {
            "name": "Min_Planta",
            "dataType": "int64",
            "sourceColumn": "Min_Planta",
            "formatString": "#,0"
          },
          {
            "type": "calculated",
            "name": "IDMetaCostos",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "CONCATENATE(CostoConversion[CuentaContable],CONCATENATE(CostoConversion[LineaID],CostoConversion[AñoSemana]))"
          },
          {
            "name": "CostoUSD",
            "dataType": "double",
            "sourceColumn": "CostoUSD"
          },
          {
            "name": "MetaCosto",
            "dataType": "double",
            "sourceColumn": "MetaCosto"
          },
          {
            "name": "MetaCostoUSD",
            "dataType": "double",
            "sourceColumn": "MetaCostoUSD"
          },
          {
            "name": "MetaTotalCosto",
            "dataType": "double",
            "sourceColumn": "MetaTotalCosto"
          },
          {
            "type": "calculated",
            "name": "Meta Produccion",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "if(CostoConversion[Piezas]<> 0, RELATED(MetasProduccionLiquidacion[ValorMeta]), 0)"
          },
          {
            "type": "calculated",
            "name": "AñoActual",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " if(CostoConversion[Año]=year(NOW()),\"S\",\"N\")"
          },
          {
            "type": "calculated",
            "name": "SemanaActual",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "if(CostoConversion[AñoSemana]=year(NOW())*100+WEEKNUM(NOW(),1)-1,\"S\",\"N\")",
              "",
              "--CALCULATE(year(NOW())*100+WEEKNUM(NOW(),1)-1)"
            ]
          }
        ],
        "partitions": [
          {
            "name": "CostoConversion",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dwh].[CostoConversion].* FROM [dwh].[CostoConversion] ",
              "dataSource": "SqlServer cubo-intermoda CRONO_INTERMODA"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>IdCostoConversion</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>152</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Linea</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>66</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CuentaContable</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>133</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TipoEmpleado</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>121</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Semana</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>84</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Seccion</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Costo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>71</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MinMeta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>84</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MinProd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>84</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MinPlanta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>92</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PiezasLeidas</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>108</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FechaAlta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>93</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FechaModificacion</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>144</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Piezas</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>71</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Min_Metas</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>98</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Min_Producidos</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>131</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Min_Planta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>100</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetaCosto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>100</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetaCostoUSD</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>127</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetaTotalCosto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>130</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CostoUSD</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>98</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>IdCostoConversion</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Linea</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CuentaContable</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TipoEmpleado</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Semana</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Seccion</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Costo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MinMeta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MinProd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MinPlanta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PiezasLeidas</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FechaAlta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FechaModificacion</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Piezas</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Min_Metas</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Min_Producidos</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Min_Planta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetaCosto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetaCostoUSD</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetaTotalCosto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CostoUSD</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>MinPlanta</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Piezas</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Min_Metas</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Min_Producidos</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Min_Planta</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetaCosto</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetaCostoUSD</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetaTotalCosto</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CostoUSD</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Minutos Meta",
            "expression": [
              " ",
              "var _anio= SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea= SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "--CALCULATE(_ultsemana)",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK() , -- && _linea<>BLANK()",
              "     CALCULATE(SUM(CostoConversion[Min_Metas]),CostoConversion[Año]=_anio, CostoConversion[Semana]=_ultsemana, CostoConversion[Linea]=_linea), ",
              "      IF(_anio <>BLANK() && _semana<>BLANK(), -- && _linea<> BLANK(),",
              "\tCALCULATE(SUM(CostoConversion[Min_Metas]),CostoConversion[Año]=_anio, CostoConversion[Semana]=_semana,CostoConversion[Linea]=_linea)\t",
              "         )",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Minutos Producidos",
            "expression": [
              " ",
              "var _anio= SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea= SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK() , -- && _linea<>BLANK()",
              "     CALCULATE(SUM(CostoConversion[Min_Producidos]),CostoConversion[Año]=_anio, CostoConversion[Semana]=_ultsemana, CostoConversion[Linea]=_linea), ",
              "      IF(_anio <>BLANK() && _semana<>BLANK(), -- && _linea<> BLANK(),",
              "\tCALCULATE(SUM(CostoConversion[Min_Producidos]),CostoConversion[Año]=_anio, CostoConversion[Semana]=_semana,CostoConversion[Linea]=_linea)\t",
              "         )",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "UnidadesLiquidadas",
            "expression": [
              "",
              "",
              "var _semana = SELECTEDVALUE(CostoConversion[AñoSemana])",
              "return",
              "",
              "CALCULATE(AVERAGE(CostoConversion[PiezasLeidas]),CostoConversion[AñoSemana]=_semana)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "CostoxSeccion",
            "expression": "sum(CostoConversion[CostoTotal])",
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Minutos Planta",
            "expression": [
              "",
              "var _anio= SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea= SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK() , -- && _linea<>BLANK()",
              "     CALCULATE(SUM(CostoConversion[Min_Planta]),CostoConversion[Año]=_anio, CostoConversion[Semana]=_ultsemana, CostoConversion[Linea]=_linea), ",
              "      IF(_anio <>BLANK() && _semana<>BLANK(), -- && _linea<> BLANK(),",
              "\tCALCULATE(SUM(CostoConversion[Min_Planta]),CostoConversion[Año]=_anio, CostoConversion[Semana]=_semana,CostoConversion[Linea]=_linea)\t",
              "         )",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Costo MOD",
            "expression": [
              " --CostoConversion[Costo Total MOD] / [Piezas Leidas MOD]",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoMOD =",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total MOD] , [Piezas Leidas MOD],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea, CostoConversion[Semana]=_ultsemana,CostoConversion[CuentaContable]=\"517\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total MOD] , [Piezas Leidas MOD],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"517\")",
              "         ) ",
              ")",
              "return",
              "IF(_costoMOD = BLANK(), 0, _costoMOD)",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo MOI",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoMOI =  ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total MOI] , [Piezas Leidas MOI],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"518\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total MOI] , [Piezas Leidas MOI],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"518\")",
              "         ) ",
              ")",
              "",
              "return",
              "IF(_costoMOI = BLANK(), 0, _costoMOI)"
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo GDF",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "var _costoGDF=",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total GDF] , [Piezas Leidas GDF],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"519\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total GDF] , [Piezas Leidas GDF],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"519\")",
              "         ) ",
              ")",
              "return",
              "",
              "IF(_costoGDF = BLANK(), 0, _costoGDF)",
              "",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo DP",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoDP =",
              " ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total DP] , [Piezas Leidas DP],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"516\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\tCALCULATE(DIVIDE([Costo Total DP] , [Piezas Leidas DP],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"516\")",
              "         )",
              ")",
              "",
              "return",
              "IF(_costoDP = BLANK(), 0 , _costoDP)"
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo CDS",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoCDS =",
              " ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(([Costo Total CDS] / [Piezas Leidas CDS]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"561\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(([Costo Total CDS] / [Piezas Leidas CDS]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"561\")",
              "         )",
              ")",
              "return",
              "IF(_costoCDS=BLANK(), 0, _costoCDS)",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PiezasLiquidadas",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]), CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK() , -- && _linea<>BLANK()",
              "     CALCULATE(SUM(CostoConversion[Piezas]),CostoConversion[Año]=_anio,  CostoConversion[Semana]=_ultsemana, CostoConversion[Linea]=_linea), ",
              "      IF(_anio <>BLANK() && _semana<>BLANK(), -- && _linea<> BLANK(),",
              "\tCALCULATE(SUM(CostoConversion[Piezas]),CostoConversion[Año]=_anio, CostoConversion[Semana]=_semana,CostoConversion[Linea]=_linea)\t",
              "         )",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Piezas Leidas MOD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE( max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              " --CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"517\")",
              "",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"517\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"517\")",
              "         ) ",
              ")",
              "",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Piezas Leidas MOI",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE( max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"518\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"518\")",
              "         ) ",
              ")",
              "",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Piezas Leidas GDF",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea]) ",
              "var _ultsemana = CALCULATE( max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              " --CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"519\")",
              "  ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"519\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"519\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Piezas Leidas DP",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              " --CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"516\")",
              "  ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"516\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"516\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Piezas Leidas CDS",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "-- CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"561\")",
              " ",
              "  ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"561\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"561\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Costo Total MOD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var  _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              " ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana,  CostoConversion[CuentaContable]=\"517\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"517\")",
              "         ) ",
              ")",
              "",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total MOI",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana,  CostoConversion[CuentaContable]=\"518\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"518\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total GDF",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "--CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio, CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"519\")",
              "",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana,  CostoConversion[CuentaContable]=\"519\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"519\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total DP",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]))",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana,  CostoConversion[CuentaContable]=\"516\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"516\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total CDS",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "--CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio, CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"561\")",
              "",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana,  CostoConversion[CuentaContable]=\"561\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"561\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total",
            "expression": " CostoConversion[Costo total MOD]+CostoConversion[Costo total MOI]+CostoConversion[Costo total GDF]+CostoConversion[Costo total DP]+CostoConversion[Costo Total CDS]",
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Piezas Leidas Acum MOD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE( max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              " --CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"517\")",
              "",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"517\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"517\")",
              "         ) ",
              ")",
              "",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Piezas Leidas Acum MOI",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE( max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              " --CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"517\")",
              "",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"518\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"518\")",
              "         ) ",
              ")",
              "",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Piezas Leidas Acum GDF",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE( max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              " --CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"517\")",
              "",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"519\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"519\")",
              "         ) ",
              ")",
              "",
              "",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Piezas Leidas Acum DP",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE( max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              " --CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"517\")",
              "",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"516\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"516\")",
              "         ) ",
              ")",
              "",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Piezas Leidas Acum CDS",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE( max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"561\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[PiezasLeidas]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"561\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total Acum MOD",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE( max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana,  CostoConversion[CuentaContable]=\"517\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"517\")",
              "         ) ",
              ")",
              "",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total Acum MOI",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana,  CostoConversion[CuentaContable]=\"518\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"518\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total Acum GDF",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana,  CostoConversion[CuentaContable]=\"519\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"519\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total Acum DP",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]), CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana,  CostoConversion[CuentaContable]=\"516\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"516\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total Acum CDS",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana,  CostoConversion[CuentaContable]=\"561\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"561\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Acum MOD",
            "expression": [
              " ",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoMOD =",
              " ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total Acum MOD] , [Piezas Leidas Acum MOD],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea, CostoConversion[Semana]<=_ultsemana,CostoConversion[CuentaContable]=\"517\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total Acum MOD], [Piezas Leidas Acum MOD],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"517\")",
              "         ) ",
              ")",
              "return",
              "IF(_costoMOD=BLANK(),0,_costoMOD)"
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Acum MOI",
            "expression": [
              "",
              "",
              "var _anio  = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoMOI =",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total Acum MOI] , [Piezas Leidas Acum MOI],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"518\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total Acum MOI] , [Piezas Leidas Acum MOI],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"518\")",
              "         ) ",
              ")",
              "",
              "return",
              "IF(_costoMOI=BLANK(),0,_costoMOI)"
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Acum GDF",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoGDF = ",
              " ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total Acum GDF] , [Piezas Leidas Acum GDF],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"519\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total Acum GDF] , [Piezas Leidas Acum GDF],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"519\")",
              "         ) ",
              ")",
              "",
              "return",
              "IF(_costoGDF=BLANK(),0,_costoGDF)"
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Acum DP",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoDP=",
              " ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total Acum DP] , [Piezas Leidas Acum DP],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"516\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total Acum DP] , [Piezas Leidas Acum DP],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"516\")",
              "         ) ",
              ")",
              "",
              "return",
              "IF(_costoDP=BLANK(),0,_costoDP)",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Acum CDS",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoCDS = ",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total Acum CDS] , [Piezas Leidas Acum CDS],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"561\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total Acum CDS] , [Piezas Leidas Acum CDS],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"561\")",
              "         )",
              ")",
              "return",
              "IF(_costoCDS=BLANK(),0,_costoCDS)",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PiezasLiquidadas Acum",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]), CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK() , -- && _linea<>BLANK()",
              "     CALCULATE(SUM(CostoConversion[Piezas]),CostoConversion[Año]=_anio,  CostoConversion[Semana]<=_ultsemana, CostoConversion[Linea]=_linea), ",
              "      IF(_anio <>BLANK() && _semana<>BLANK(), -- && _linea<> BLANK(),",
              "\tCALCULATE(SUM(CostoConversion[Piezas]),CostoConversion[Año]=_anio, CostoConversion[Semana]<=_semana,CostoConversion[Linea]=_linea)\t",
              "         )",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Costo Conversion Por Pieza",
            "expression": [
              " CostoConversion[Costo MOD]+CostoConversion[Costo MOI]+CostoConversion[Costo GDF]+CostoConversion[Costo DP]+CostoConversion[Costo CDS]",
              "/*",
              "var _totcosto = CostoConversion[Costo MOD]+CostoConversion[Costo MOI]+CostoConversion[Costo GDF]+CostoConversion[Costo DP]+CostoConversion[Costo CDS]",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK() , -- && _linea<>BLANK()",
              "     CALCULATE(_totcosto,CostoConversion[Año]=_anio, CostoConversion[Semana]<=_ultsemana, CostoConversion[Linea]=_linea), ",
              "      IF(_anio <>BLANK() && _semana<>BLANK(), -- && _linea<> BLANK(),",
              "\tCALCULATE(_totcosto,CostoConversion[Año]=_anio, CostoConversion[Semana]<=_semana,CostoConversion[Linea]=_linea)\t",
              "         )",
              ")",
              "*/"
            ],
            "formatString": "0.00"
          },
          {
            "name": "Minutos Producidos Acum",
            "expression": [
              " ",
              "var _anio= SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea= SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK() , -- && _linea<>BLANK()",
              "     CALCULATE(SUM(CostoConversion[Min_Producidos]),CostoConversion[Año]=_anio, CostoConversion[Semana]<=_ultsemana, CostoConversion[Linea]=_linea), ",
              "      IF(_anio <>BLANK() && _semana<>BLANK(), -- && _linea<> BLANK(),",
              "\tCALCULATE(SUM(CostoConversion[Min_Producidos]),CostoConversion[Año]=_anio, CostoConversion[Semana]<=_semana,CostoConversion[Linea]=_linea)\t",
              "         )",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Minutos Planeados Acum",
            "expression": [
              " ",
              "var _anio= SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea= SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK() , -- && _linea<>BLANK()",
              "     CALCULATE(SUM(CostoConversion[Min_Metas]),CostoConversion[Año]=_anio, CostoConversion[Semana]<=_ultsemana, CostoConversion[Linea]=_linea), ",
              "      IF(_anio <>BLANK() && _semana<>BLANK(), -- && _linea<> BLANK(),",
              "\tCALCULATE(SUM(CostoConversion[Min_Metas]),CostoConversion[Año]=_anio, CostoConversion[Semana]<=_semana,CostoConversion[Linea]=_linea)\t",
              "         )",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Minutos Planta Acum",
            "expression": [
              " ",
              "var _anio= SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea= SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK() , -- && _linea<>BLANK()",
              "     CALCULATE(SUM(CostoConversion[Min_Planta]),CostoConversion[Año]=_anio, CostoConversion[Semana]<=_ultsemana, CostoConversion[Linea]=_linea), ",
              "      IF(_anio <>BLANK() && _semana<>BLANK(), -- && _linea<> BLANK(),",
              "\tCALCULATE(SUM(CostoConversion[Min_Planta]),CostoConversion[Año]=_anio, CostoConversion[Semana]<=_semana,CostoConversion[Linea]=_linea)\t",
              "         )",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Costo Total Acum",
            "expression": " CostoConversion[Costo total Acum MOD]+CostoConversion[Costo total Acum MOI]+CostoConversion[Costo total Acum GDF]+CostoConversion[Costo total Acum DP]+CostoConversion[Costo total Acum CDS]",
            "formatString": "#,0.00"
          },
          {
            "name": "Costo por Minuto Producido",
            "expression": " DIVIDE( CostoConversion[Costo Total],[Minutos Producidos],0)",
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Por Prenda",
            "expression": "DIVIDE( [Minutos Producidos],[PiezasLiquidadas],0)",
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Por Prenda Acum",
            "expression": " DIVIDE( [Minutos Producidos Acum],[PiezasLiquidadas Acum],0)",
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo por Minuto Producido Acum",
            "expression": "DIVIDE(CostoConversion[Costo Total Acum] , [Minutos Producidos Acum],0)",
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total MOD USD",
            "expression": [
              " ",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var  _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              " ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana,  CostoConversion[CuentaContable]=\"517\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"517\")",
              "         ) ",
              ")",
              "",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo MOD USD",
            "expression": [
              " --CostoConversion[Costo Total MOD] / [Piezas Leidas MOD]",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoMOD = ",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total MOD USD] , [Piezas Leidas MOD],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea, CostoConversion[Semana]=_ultsemana,CostoConversion[CuentaContable]=\"517\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total MOD USD] , [Piezas Leidas MOD],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"517\")",
              "         ) ",
              ")",
              "return",
              "IF(_costoMOD=BLANK(),0,_costoMOD)",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total MOI USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "--CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio, CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"518\")",
              "",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana,  CostoConversion[CuentaContable]=\"518\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"518\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo MOI USD",
            "expression": [
              "",
              "var _anio  = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoMOI = ",
              " ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total MOI USD] , [Piezas Leidas MOI],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"518\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total MOI USD] , [Piezas Leidas MOI],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"518\")",
              "         ) ",
              ")",
              "",
              "return",
              "IF(_costoMOI=BLANK(),0,_costoMOI)"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total GDF USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "--CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio, CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"519\")",
              "",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana,  CostoConversion[CuentaContable]=\"519\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"519\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo GDF USD",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoGDF =",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total GDF USD] , [Piezas Leidas GDF],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"519\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total GDF USD] , [Piezas Leidas GDF],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"519\")",
              "         ) ",
              ")",
              "return",
              "IF(_costoGDF=BLANK(),0,_costoGDF)",
              "",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total DP USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]), CostoConversion[Año]=_anio)",
              "return",
              "",
              "--CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio, CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"516\")",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana,  CostoConversion[CuentaContable]=\"516\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"516\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo DP USD",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoDP =",
              " ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total DP USD] , [Piezas Leidas DP],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"516\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total DP USD] , [Piezas Leidas DP],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"516\")",
              "         ) ",
              ")",
              "return",
              "IF(_costoDP=BLANK(),0,_costoDP)"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total CDS USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "--CALCULATE(sum(CostoConversion[Costo]),CostoConversion[Año]=_anio, CostoConversion[Linea]=_linea, CostoConversion[CuentaContable]=\"561\")",
              "",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_ultsemana,  CostoConversion[CuentaContable]=\"561\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"561\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo CDS USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "var _costoCDS = ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total CDS USD] , [Piezas Leidas CDS],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]=_ultsemana, CostoConversion[CuentaContable]=\"561\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total CDS USD] ,[Piezas Leidas CDS],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]=_semana, CostoConversion[CuentaContable]=\"561\")",
              "         )",
              ")",
              "",
              "return",
              "IF(_costoCDS=BLANK(),0,_costoCDS)"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total Acum MOD USD",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE( max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana,  CostoConversion[CuentaContable]=\"517\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"517\")",
              "         ) ",
              ")",
              "",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Acum MOD USD",
            "expression": [
              " --CostoConversion[Costo Total MOD] / [Piezas Leidas MOD]",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoMOD=",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total Acum MOD USD] , [Piezas Leidas Acum MOD],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea, CostoConversion[Semana]<=_ultsemana,CostoConversion[CuentaContable]=\"517\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total Acum MOD USD] , [Piezas Leidas Acum MOD],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"517\")",
              "         ) ",
              ")",
              "return",
              "",
              "IF(_costoMOD=BLANK(),0,_costoMOD)",
              "",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total Acum MOI USD",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana,  CostoConversion[CuentaContable]=\"518\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"518\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Acum MOI USD",
            "expression": [
              "",
              "",
              "var _anio  = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoMOI =",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(([Costo Total Acum MOI USD] / [Piezas Leidas Acum MOI]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"518\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(([Costo Total Acum MOI USD] / [Piezas Leidas Acum MOI]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"518\")",
              "         ) ",
              ")",
              "",
              "return",
              "IF(_costoMOI=BLANK(), 0 ,_costoMOI)"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total Acum GDF USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana,  CostoConversion[CuentaContable]=\"519\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"519\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Acum GDF USD",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoGDF=",
              " ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total Acum GDF USD] , [Piezas Leidas Acum GDF],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"519\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total Acum GDF USD] , [Piezas Leidas Acum GDF],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"519\")",
              "         ) ",
              ")",
              "",
              "return",
              "IF(_costoGDF=BLANK(),0,_costoGDF)",
              "",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total Acum DP USD",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]), CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana,  CostoConversion[CuentaContable]=\"516\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"516\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Acum DP USD",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "var _costoDP=",
              " ",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total Acum DP USD] , [Piezas Leidas Acum DP],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"516\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total Acum DP USD] , [Piezas Leidas Acum DP],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"516\")",
              "         ) ",
              ")",
              "",
              "return",
              "IF(_costoDP=BLANK(), 0 ,_costoDP)"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total Acum CDS USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(max(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_ultsemana,  CostoConversion[CuentaContable]=\"561\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(sum(CostoConversion[CostoUSD]),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"561\")",
              "         ) ",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Acum CDS USD",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "var _costoCDS =",
              "IF(_anio<> BLANK()  && _semana=BLANK(),",
              "    CALCULATE(DIVIDE([Costo Total Acum CDS USD] , [Piezas Leidas Acum CDS],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,  CostoConversion[Semana]<=_ultsemana, CostoConversion[CuentaContable]=\"561\"),",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(DIVIDE([Costo Total Acum CDS USD] , [Piezas Leidas Acum CDS],0),CostoConversion[Año]=_anio,  CostoConversion[Linea]=_linea,CostoConversion[Semana]<=_semana, CostoConversion[CuentaContable]=\"561\")",
              "         )",
              ")",
              "",
              "return",
              "IF(_costoCDS=BLANK(), 0 , _costoCDS)"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo MOI",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=518), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=518)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo MOD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=517), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=517)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo GDF",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=519), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=519)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo DP",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=516), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=516)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo CDS",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=561), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=561)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo MOD USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=517), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=517)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo MOI USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=518), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=518)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo GDF USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=519), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=519)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo DP USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=516), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=516)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo CDS USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=561), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=561)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo Acum MOD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_ultsemana,MetasCostosConversion[Cuenta]=517), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_semana,MetasCostosConversion[Cuenta]=517)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo Acum MOI",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            ",
              "      CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_ultsemana,MetasCostosConversion[Cuenta]=518), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_semana,MetasCostosConversion[Cuenta]=518)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo Acum GDF",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_ultsemana,MetasCostosConversion[Cuenta]=519), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_semana,MetasCostosConversion[Cuenta]=519)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo Acum DP",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(), ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_ultsemana,MetasCostosConversion[Cuenta]=516), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_semana,MetasCostosConversion[Cuenta]=516)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo Acum CDS",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            ",
              "        CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_ultsemana,MetasCostosConversion[Cuenta]=561), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_semana,MetasCostosConversion[Cuenta]=561)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "MetaCostoTotal",
            "expression": " AVERAGE(CostoConversion[MetaTotalCosto])",
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Total Conversion",
            "expression": "sum(CostoConversion[CostoTotal])",
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo Acum MOD USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_ultsemana,MetasCostosConversion[Cuenta]=517), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_semana,MetasCostosConversion[Cuenta]=517)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo Acum MOI USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            ",
              "      CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_ultsemana,MetasCostosConversion[Cuenta]=518), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_semana,MetasCostosConversion[Cuenta]=518)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo Acum GDF USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_ultsemana,MetasCostosConversion[Cuenta]=519), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_semana,MetasCostosConversion[Cuenta]=519)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo Acum DP USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(), ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_ultsemana,MetasCostosConversion[Cuenta]=516), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_semana,MetasCostosConversion[Cuenta]=516)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Meta Costo Acum CDS USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),            ",
              "        CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_ultsemana,MetasCostosConversion[Cuenta]=561), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]<=_semana,MetasCostosConversion[Cuenta]=561)",
              "        )",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Ultima Semana",
            "expression": [
              "",
              "var _anio= SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea= SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "CALCULATE(_ultsemana)"
            ]
          },
          {
            "name": "Costo Por Prenda USD",
            "expression": "(DIVIDE( [Minutos Producidos],[PiezasLiquidadas],0))/(sum(CostoConversion[MetaCostoUSD]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"21514\" DisplayName=\"$ Español (Estados Unidos)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Eficiencia Planeada",
            "expression": " DIVIDE([Minutos Producidos] , [Minutos Planta])",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "Minutos Perdidos",
            "expression": " [Minutos Meta] - [Minutos Producidos]",
            "formatString": "0"
          },
          {
            "name": "Costo Esperado",
            "expression": "DIVIDE(CostoConversion[Costo Total] , [Minutos Meta],0)",
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Costo Esperado Acum",
            "expression": "DIVIDE(CostoConversion[Costo Total Acum] , [Minutos Planeados Acum],0)",
            "formatString": "\"L\"#,0.00;-\"L\"#,0.00;\"L\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"18442\" DisplayName=\"L Español (Honduras)\" Symbol=\"L\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Minutos Perdidos Acum",
            "expression": " [Minutos Planeados Acum] - [Minutos Producidos Acum]",
            "formatString": "0"
          },
          {
            "name": "Variacion Produccion Minutos",
            "expression": " (([Minutos Producidos] - [Minutos Meta])  / [Minutos Meta])*100",
            "formatString": "0.00"
          },
          {
            "name": "Variacion Produccion Piezas",
            "expression": " (([PiezasLiquidadas] - [Metas Piezas Liquidadas]) / MetasProduccionLiquidacion[Metas Piezas Liquidadas])*100",
            "formatString": "0.00"
          },
          {
            "name": "Total Piezas Liquidadas",
            "expression": [
              " SUM(CostoConversion[Piezas])",
              "/*",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]), CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK() , -- && _linea<>BLANK()",
              "     CALCULATE(SUM(CostoConversion[Piezas]),CostoConversion[Año]=_anio,  CostoConversion[Semana]=_ultsemana, CostoConversion[Linea]=_linea), ",
              "      IF(_anio <>BLANK() && _semana<>BLANK(), -- && _linea<> BLANK(),",
              "\tCALCULATE(SUM(CostoConversion[Piezas]),CostoConversion[Año]=_anio, CostoConversion[Semana]=_semana,CostoConversion[Linea]=_linea)\t",
              "         )",
              ")",
              "*/"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Meta Produccion Prom",
            "expression": " CALCULATE(SUM(CostoConversion[Meta Produccion]))",
            "formatString": "#,0"
          },
          {
            "name": "Total Minutos Producidos",
            "expression": [
              " SUM(CostoConversion[MinProd])",
              "",
              "/*",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[Linea])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]), CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK() , -- && _linea<>BLANK()",
              "     CALCULATE(SUM(CostoConversion[Piezas]),CostoConversion[Año]=_anio,  CostoConversion[Semana]=_ultsemana, CostoConversion[Linea]=_linea), ",
              "      IF(_anio <>BLANK() && _semana<>BLANK(), -- && _linea<> BLANK(),",
              "\tCALCULATE(SUM(CostoConversion[Piezas]),CostoConversion[Año]=_anio, CostoConversion[Semana]=_semana,CostoConversion[Linea]=_linea)\t",
              "         )",
              ")",
              "*/"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Eficiencia Planeada Acum",
            "expression": " DIVIDE([Minutos Producidos Acum],[Minutos Planeados Acum])",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "Variacion Produccion Minutos Acum",
            "expression": " (([Minutos Producidos Acum] - [Minutos Planeados Acum])  / [Minutos Planeados Acum])*100",
            "formatString": "0.00"
          },
          {
            "name": "Variacion Produccion Piezas Acum",
            "expression": " (([PiezasLiquidadas Acum] - [Metas Piezas Liquidadas Acum]) / MetasProduccionLiquidacion[Metas Piezas Liquidadas Acum])*100",
            "formatString": "0.00"
          },
          {
            "name": "Minutos Produccion Metas",
            "expression": " sum(CostoConversion[Min_Metas])",
            "formatString": "#,0"
          },
          {
            "name": "Minutos Produccion",
            "expression": " sum(CostoConversion[Min_Producidos])",
            "formatString": "#,0"
          },
          {
            "name": "Total Costo Conversion",
            "expression": " [Costo MOD]+[Costo MOI]+[Costo GDF]+[Costo DP]+[Costo CDS]"
          },
          {
            "name": "Total Meta Costo Conversion",
            "expression": " [Meta Costo MOD]+[Meta Costo MOI]+[Meta Costo DP]+[Meta Costo GDF]+[Meta Costo CDS]"
          },
          {
            "name": "Total Costo Acum",
            "expression": " [Costo Acum MOD]+[Costo Acum MOI]+[Costo Acum DP]+[Costo Acum GDF]+[Costo Acum CDS]"
          },
          {
            "name": "Total Meta Acum",
            "expression": " [Meta Costo Acum MOD]+[Meta Costo Acum MOI]+[Meta Costo Acum DP]+[Meta Costo Acum DP]+[Meta Costo Acum CDS]"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dwh].[CostoConversion].* FROM [dwh].[CostoConversion] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "CostoConversion"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dwh"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>IdCostoConversion</string>",
              "      </key>",
              "      <value>",
              "        <int>152</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Linea</string>",
              "      </key>",
              "      <value>",
              "        <int>66</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CuentaContable</string>",
              "      </key>",
              "      <value>",
              "        <int>133</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TipoEmpleado</string>",
              "      </key>",
              "      <value>",
              "        <int>121</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Semana</string>",
              "      </key>",
              "      <value>",
              "        <int>84</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Seccion</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Costo</string>",
              "      </key>",
              "      <value>",
              "        <int>71</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MinMeta</string>",
              "      </key>",
              "      <value>",
              "        <int>84</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MinProd</string>",
              "      </key>",
              "      <value>",
              "        <int>84</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MinPlanta</string>",
              "      </key>",
              "      <value>",
              "        <int>92</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PiezasLeidas</string>",
              "      </key>",
              "      <value>",
              "        <int>108</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FechaAlta</string>",
              "      </key>",
              "      <value>",
              "        <int>93</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FechaModificacion</string>",
              "      </key>",
              "      <value>",
              "        <int>144</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Piezas</string>",
              "      </key>",
              "      <value>",
              "        <int>71</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Min_Metas</string>",
              "      </key>",
              "      <value>",
              "        <int>98</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Min_Producidos</string>",
              "      </key>",
              "      <value>",
              "        <int>131</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Min_Planta</string>",
              "      </key>",
              "      <value>",
              "        <int>100</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetaCosto</string>",
              "      </key>",
              "      <value>",
              "        <int>100</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetaCostoUSD</string>",
              "      </key>",
              "      <value>",
              "        <int>127</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetaTotalCosto</string>",
              "      </key>",
              "      <value>",
              "        <int>130</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CostoUSD</string>",
              "      </key>",
              "      <value>",
              "        <int>98</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>IdCostoConversion</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Linea</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CuentaContable</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TipoEmpleado</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Semana</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Seccion</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Costo</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MinMeta</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MinProd</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MinPlanta</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PiezasLeidas</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FechaAlta</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FechaModificacion</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Piezas</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Min_Metas</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Min_Producidos</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Min_Planta</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetaCosto</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetaCostoUSD</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetaTotalCosto</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CostoUSD</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>MinPlanta</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Piezas</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Min_Metas</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Min_Producidos</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Min_Planta</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetaCosto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetaCostoUSD</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetaTotalCosto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CostoUSD</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "MetasCostosConversion",
        "columns": [
          {
            "name": "Cuenta",
            "dataType": "double",
            "sourceColumn": "Cuenta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Año",
            "dataType": "double",
            "sourceColumn": "Año",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Semana",
            "dataType": "double",
            "sourceColumn": "Semana",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Linea",
            "dataType": "string",
            "sourceColumn": "Linea",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Meta",
            "dataType": "double",
            "sourceColumn": "Meta",
            "sourceProviderType": "Numeric"
          },
          {
            "type": "calculated",
            "name": "AñoSemana",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "MetasCostosConversion[Año]*100+MetasCostosConversion[Semana]"
          },
          {
            "type": "calculated",
            "name": "LineaID",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "SWITCH(MetasCostosConversion[Linea],\"Denim\", 10, \"Tejido Punto\", 34, \"Estampado\",35)"
          },
          {
            "type": "calculated",
            "name": "IDMetaCostos",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "CONCATENATE(MetasCostosConversion[Cuenta], CONCATENATE(MetasCostosConversion[LineaID],MetasCostosConversion[AñoSemana]))"
          },
          {
            "name": "MetaUSD",
            "dataType": "double",
            "sourceColumn": "MetaUSD"
          }
        ],
        "partitions": [
          {
            "name": "MetasCostosConversion",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dwh].[MetasCostosConversion].[cuenta],[dwh].[MetasCostosConversion].[año],[dwh].[MetasCostosConversion].[semana],[dwh].[MetasCostosConversion].[linea],[dwh].[MetasCostosConversion].[Meta],[dwh].[MetasCostosConversion].[MetaUSD] FROM [dwh].[MetasCostosConversion] ",
              "dataSource": "SqlServer cubo-intermoda"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Meta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>64</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetaUSD</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>linea</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>61</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AñoSemana</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>108</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>semana</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>año</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>58</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>cuenta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>77</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Meta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetaUSD</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>linea</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AñoSemana</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>semana</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>año</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>cuenta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Meta</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetaUSD</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AñoSemana</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "MetaTotal",
            "expression": " sum(MetasCostosConversion[Meta])"
          },
          {
            "name": "Meta MOD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(MetasCostosConversion[Año])",
              "var _semana = SELECTEDVALUE(MetasCostosConversion[Semana])",
              "var _linea = SELECTEDVALUE(MetasCostosConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(MetasCostosConversion[Semana]),MetasCostosConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),    ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=517), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=517)",
              "         ) ",
              ")",
              "",
              ""
            ]
          },
          {
            "name": "Meta MOI",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),    ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=518), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=518)",
              "         )",
              ")",
              ""
            ]
          },
          {
            "name": "Meta GDF",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),    ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=519), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=519)",
              "         )",
              ")",
              ""
            ]
          },
          {
            "name": "Meta DP",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),   ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=516), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=516)",
              "         )",
              ")",
              ""
            ]
          },
          {
            "name": "Meta CDS",
            "expression": [
              "",
              "",
              "var _anio = SELECTEDVALUE(CostoConversion[Año])",
              "var _semana = SELECTEDVALUE(CostoConversion[Semana])",
              "var _linea = SELECTEDVALUE(CostoConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),    ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=561), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[Meta]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=561)",
              "         )",
              ")",
              ""
            ]
          },
          {
            "name": "Meta Total USD",
            "expression": " sum(MetasCostosConversion[MetaUSD])"
          },
          {
            "name": "Meta MOD USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(MetasCostosConversion[Año])",
              "var _semana = SELECTEDVALUE(MetasCostosConversion[Semana])",
              "var _linea = SELECTEDVALUE(MetasCostosConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(MetasCostosConversion[Semana]),MetasCostosConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),    ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=517), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=517)",
              "         ) ",
              ")",
              "",
              ""
            ]
          },
          {
            "name": "Meta MOI USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(MetasCostosConversion[Año])",
              "var _semana = SELECTEDVALUE(MetasCostosConversion[Semana])",
              "var _linea = SELECTEDVALUE(MetasCostosConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(MetasCostosConversion[Semana]),MetasCostosConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),   ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=518), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=518)",
              "         )",
              ")",
              "",
              ""
            ]
          },
          {
            "name": "Meta GDF USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(MetasCostosConversion[Año])",
              "var _semana = SELECTEDVALUE(MetasCostosConversion[Semana])",
              "var _linea = SELECTEDVALUE(MetasCostosConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(MetasCostosConversion[Semana]),MetasCostosConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),   ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=519), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=519)",
              "         )",
              ")",
              ""
            ]
          },
          {
            "name": "Meta DP USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(MetasCostosConversion[Año])",
              "var _semana = SELECTEDVALUE(MetasCostosConversion[Semana])",
              "var _linea = SELECTEDVALUE(MetasCostosConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(MetasCostosConversion[Semana]),MetasCostosConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),   ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=516), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=516)",
              "         )",
              ")",
              ""
            ]
          },
          {
            "name": "Meta CDS USD",
            "expression": [
              "",
              "var _anio = SELECTEDVALUE(MetasCostosConversion[Año])",
              "var _semana = SELECTEDVALUE(MetasCostosConversion[Semana])",
              "var _linea = SELECTEDVALUE(MetasCostosConversion[LineaID])",
              "var _ultsemana = CALCULATE(MAX(MetasCostosConversion[Semana]),MetasCostosConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<> BLANK()  && _semana=BLANK(),               ",
              "       CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_ultsemana,MetasCostosConversion[Cuenta]=561), ",
              "       IF(_anio<> BLANK() && _semana<>BLANK(),",
              "\t CALCULATE(AVERAGE(MetasCostosConversion[MetaUSD]),MetasCostosConversion[Año]=_anio,MetasCostosConversion[LineaID]=_linea,MetasCostosConversion[Semana]=_semana,MetasCostosConversion[Cuenta]=561)",
              "         )",
              ")",
              ""
            ],
            "formatString": "0.00"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dwh].[MetasCostosConversion].[cuenta],[dwh].[MetasCostosConversion].[año],[dwh].[MetasCostosConversion].[semana],[dwh].[MetasCostosConversion].[linea],[dwh].[MetasCostosConversion].[Meta],[dwh].[MetasCostosConversion].[MetaUSD] FROM [dwh].[MetasCostosConversion] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "MetasCostosConversion"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dwh"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Meta</string>",
              "      </key>",
              "      <value>",
              "        <int>64</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetaUSD</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>linea</string>",
              "      </key>",
              "      <value>",
              "        <int>61</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AñoSemana</string>",
              "      </key>",
              "      <value>",
              "        <int>108</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>semana</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>año</string>",
              "      </key>",
              "      <value>",
              "        <int>58</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>cuenta</string>",
              "      </key>",
              "      <value>",
              "        <int>77</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Meta</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetaUSD</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>linea</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AñoSemana</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>semana</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>año</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>cuenta</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Meta</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetaUSD</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AñoSemana</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "MetasProduccionLiquidacion",
        "columns": [
          {
            "name": "IdLinea",
            "dataType": "double",
            "sourceColumn": "IdLinea",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Descripcion",
            "dataType": "string",
            "sourceColumn": "Descripcion",
            "sourceProviderType": "WChar"
          },
          {
            "name": "FechaDesde",
            "dataType": "dateTime",
            "sourceColumn": "FechaDesde",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "FechaHasta",
            "dataType": "dateTime",
            "sourceColumn": "FechaHasta",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "ValorMeta",
            "dataType": "double",
            "sourceColumn": "ValorMeta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Semana",
            "dataType": "int64",
            "sourceColumn": "Semana"
          },
          {
            "name": "Año",
            "dataType": "int64",
            "sourceColumn": "Año"
          },
          {
            "type": "calculated",
            "name": "IDLineaAñoSemana",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "CONCATENATE(MetasProduccionLiquidacion[IDLinea],(MetasProduccionLiquidacion[Año]*100+MetasProduccionLiquidacion[Semana]))"
          }
        ],
        "partitions": [
          {
            "name": "MetasProduccionLiquidacion",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dwh].[MetasProduccionLiquidacion].* FROM [dwh].[MetasProduccionLiquidacion] ",
              "dataSource": "SqlServer cubo-intermoda CRONO_INTERMODA"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>IdLinea</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Descripcion</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FechaDesde</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>109</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FechaHasta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ValorMeta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>94</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Semana</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>84</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Año</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>59</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>IdLinea</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Descripcion</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FechaDesde</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FechaHasta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ValorMeta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Semana</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Año</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Semana</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Año</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Metas Piezas Liquidadas",
            "expression": [
              "",
              "var _anio= VALUE(SELECTEDVALUE(CostoConversion[Año]))",
              "var _semana = VALUE(SELECTEDVALUE(CostoConversion[Semana]))",
              "var _linea =VALUE(SELECTEDVALUE(CostoConversion[LineaID]))",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK(),",
              "    CALCULATE(SUM(MetasProduccionLiquidacion[ValorMeta]),MetasProduccionLiquidacion[Año]=_anio,MetasProduccionLiquidacion[IDLinea]=_linea, MetasProduccionLiquidacion[Semana] = _ultsemana),    ",
              "       IF(_anio<>BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(SUM(MetasProduccionLiquidacion[ValorMeta]),MetasProduccionLiquidacion[Año]=_anio, MetasProduccionLiquidacion[Semana]=_semana, MetasProduccionLiquidacion[IDLinea]=_linea)",
              "         ) ",
              ")",
              "",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Metas Piezas Liquidadas Acum",
            "expression": [
              "",
              "",
              "var _anio= VALUE(SELECTEDVALUE(CostoConversion[Año]))",
              "var _semana = VALUE(SELECTEDVALUE(CostoConversion[Semana]))",
              "var _linea =VALUE(SELECTEDVALUE(CostoConversion[LineaID]))",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "--CALCULATE(_ultsemana)",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK(),",
              "    CALCULATE(SUM(MetasProduccionLiquidacion[ValorMeta]),MetasProduccionLiquidacion[Año]=_anio,MetasProduccionLiquidacion[IDLinea]=_linea, MetasProduccionLiquidacion[Semana] <= _ultsemana),    ",
              "       IF(_anio<>BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(SUM(MetasProduccionLiquidacion[ValorMeta]),MetasProduccionLiquidacion[Año]=_anio, MetasProduccionLiquidacion[Semana]<=_semana, MetasProduccionLiquidacion[IDLinea]=_linea)",
              "         ) ",
              ")",
              "",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Total Metas Piezas Liquidadas",
            "expression": [
              " SUM(MetasProduccionLiquidacion[ValorMeta])",
              "/*",
              "var _anio= VALUE(SELECTEDVALUE(CostoConversion[Año]))",
              "var _semana = VALUE(SELECTEDVALUE(CostoConversion[Semana]))",
              "var _linea =VALUE(SELECTEDVALUE(CostoConversion[LineaID]))",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK(),",
              "    CALCULATE(SUM(MetasProduccionLiquidacion[ValorMeta]),MetasProduccionLiquidacion[Año]=_anio,MetasProduccionLiquidacion[IDLinea]=_linea, MetasProduccionLiquidacion[Semana] <= _ultsemana),    ",
              "       IF(_anio<>BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(SUM(MetasProduccionLiquidacion[ValorMeta]),MetasProduccionLiquidacion[Año]=_anio, MetasProduccionLiquidacion[Semana]<=_semana, MetasProduccionLiquidacion[IDLinea]=_linea)",
              "         ) ",
              ")",
              "*/"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Total Metas Piezas Liquidadas Acum",
            "expression": [
              "",
              "",
              "var _anio= VALUE(SELECTEDVALUE(CostoConversion[Año]))",
              "var _semana = VALUE(SELECTEDVALUE(CostoConversion[Semana]))",
              "var _linea =VALUE(SELECTEDVALUE(CostoConversion[LineaID]))",
              "var _ultsemana = CALCULATE(MAX(CostoConversion[Semana]),CostoConversion[Año]=_anio)",
              "return",
              "",
              "IF(_anio<>BLANK()  && _semana=BLANK(),",
              "    CALCULATE(SUM(MetasProduccionLiquidacion[ValorMeta]),MetasProduccionLiquidacion[Año]=_anio,MetasProduccionLiquidacion[IDLinea]=_linea, MetasProduccionLiquidacion[Semana] <= _ultsemana),    ",
              "       IF(_anio<>BLANK() && _semana<>BLANK(),",
              "\t  CALCULATE(SUM(MetasProduccionLiquidacion[ValorMeta]),MetasProduccionLiquidacion[Año]=_anio, MetasProduccionLiquidacion[Semana]<=_semana, MetasProduccionLiquidacion[IDLinea]=_linea)",
              "         ) ",
              ")",
              "",
              ""
            ],
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dwh].[MetasProduccionLiquidacion].* FROM [dwh].[MetasProduccionLiquidacion] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "MetasProduccionLiquidacion"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dwh"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>IdLinea</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Descripcion</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FechaDesde</string>",
              "      </key>",
              "      <value>",
              "        <int>109</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FechaHasta</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ValorMeta</string>",
              "      </key>",
              "      <value>",
              "        <int>94</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Semana</string>",
              "      </key>",
              "      <value>",
              "        <int>84</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Año</string>",
              "      </key>",
              "      <value>",
              "        <int>59</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>IdLinea</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Descripcion</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FechaDesde</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FechaHasta</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ValorMeta</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Semana</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Año</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Semana</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Año</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "6c349662-b58c-46c1-8ba0-e83e96b018bc",
        "fromTable": "CostoConversion",
        "fromColumn": "IDMetaCostos",
        "toTable": "MetasCostosConversion",
        "toColumn": "IDMetaCostos"
      },
      {
        "name": "bf05a14d-ee86-44e7-bd4b-35d396f3689f",
        "fromTable": "CostoConversion",
        "fromColumn": "IDLineaAñoSemana",
        "toTable": "MetasProduccionLiquidacion",
        "toColumn": "IDLineaAñoSemana"
      }
    ],
    "roles": [
      {
        "name": "Analistas",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "INTERMODA\\ezaldivar",
            "memberId": "S-1-5-21-558972960-1907833099-1335851356-14675"
          },
          {
            "memberName": "INTERMODA\\ilainez",
            "memberId": "S-1-5-21-558972960-1907833099-1335851356-16300"
          },
          {
            "memberName": "INTERMODA\\jcastellanos",
            "memberId": "S-1-5-21-558972960-1907833099-1335851356-15063"
          },
          {
            "memberName": "INTERMODA\\adaniel",
            "memberId": "S-1-5-21-558972960-1907833099-1335851356-14629"
          }
        ]
      },
      {
        "name": "Gerencia",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "INTERMODA\\ffernandez",
            "memberId": "S-1-5-21-558972960-1907833099-1335851356-1221"
          },
          {
            "memberName": "INTERMODA\\nchahin",
            "memberId": "S-1-5-21-558972960-1907833099-1335851356-1350"
          },
          {
            "memberName": "INTERMODA\\lavila",
            "memberId": "S-1-5-21-558972960-1907833099-1335851356-1327"
          },
          {
            "memberName": "INTERMODA\\opaz",
            "memberId": "S-1-5-21-558972960-1907833099-1335851356-16357"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}